name: Continuous Integration
on:
  push:
    branches: [magnet]
  pull_request:
    branches: [magnet]
jobs:
  build:
    name: Integrate Continuously
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sha256sum README.md
